SELECT * FROM beanionsdb.members;

-- 전체 회원수(관리자 포함) --
SELECT COUNT(*) FROM MEMBERS;

-- 전체 회원수(관리자 미포함) --
SELECT COUNT(MEMBER_ROLE)
  FROM MEMBERS
 WHERE MEMBER_ROLE = 'USER';
 
SELECT * FROM beanionsdb.post;
 
-- 전체 게시글수 --
SELECT COUNT(*) FROM POST;
 
-- 전체 리뷰글수 --
SELECT COUNT(MAIN_CATEGORY)
  FROM POST
 WHERE MAIN_CATEGORY = '리뷰';
 
-- 전체 자유글수 --
SELECT COUNT(MAIN_CATEGORY)
  FROM POST
 WHERE MAIN_CATEGORY = '자유';
 
-- 전체 예랑글수 --
SELECT COUNT(SUB_CATEGORY)
  FROM POST
 WHERE SUB_CATEGORY = '예랑';
 
-- 전체 예신글수 --
SELECT COUNT(SUB_CATEGORY)
  FROM POST
 WHERE SUB_CATEGORY = '예신';
 
-- 전체 매거진글수 --
SELECT COUNT(MAIN_CATEGORY)
  FROM POST
 WHERE MAIN_CATEGORY = '매거진';
 
-- 전체 매거진글수 --
SELECT COUNT(MAIN_CATEGORY)
  FROM POST
 WHERE MAIN_CATEGORY = '공지사항';
 
-- 오늘 가입한 회원 수--
SELECT COUNT(SIGNUP_DATE)
  FROM MEMBERS
 WHERE SIGNUP_DATE = '2024-04-11'; -- 오늘 날짜

-- 오늘 게시물 수 --
SELECT COUNT(POST_DATE)
  FROM POST
 WHERE POST_DATE = '2024-04-11';  -- 오늘 날짜
 

-- 게시글 전체 조회(자유, 리뷰) --
SELECT 
       A.MAIN_CATEGORY
	 , A.SUB_CATEGORY
     , A.POST_TITLE
     , B.NICKNAME
     , A.POST_DATE
     , A.VEF_STATUS
  FROM POST A
  JOIN MEMBERS B ON A.MEMBER_CODE = B.MEMBER_CODE
 WHERE MAIN_CATEGORY = '자유' OR  MAIN_CATEGORY = '리뷰'
 ORDER BY POST_DATE DESC;
 
 SELECT 
       A.MAIN_CATEGORY
	 , A.SUB_CATEGORY
     , A.POST_TITLE
     , B.NICKNAME
     , A.POST_DATE
     , A.VEF_STATUS
  FROM POST A
 LEFT JOIN MEMBERS B ON A.MEMBER_CODE = B.MEMBER_CODE
 WHERE MAIN_CATEGORY = '자유' OR  MAIN_CATEGORY = '리뷰'
 ORDER BY POST_DATE DESC;
 
 
 
         SELECT
        A.POST_CODE
        , A.MEMBER_CODE
        , A.POST_TITLE
        , A.POST_CONTEXT
        , A.POST_DATE
        , A.MAIN_CATEGORY
        , A.SUB_CATEGORY
        , A.VEF_STATUS
        , B.MEMBER_CODE
        , B.NICKNAME
        FROM POST A
        LEFT JOIN MEMBERS B ON (A.MEMBER_CODE = B.MEMBER_CODE)
        WHERE POST_CODE = 37;
